CREATE TABLE AGENDA(
    ID       SERIAL PRIMARY KEY,
    USERNAME VARCHAR(30) NOT NULL,
    DAY      VARCHAR(9),
    TIME     VARCHAR(5) NOT NULL,
    NOTE     VARCHAR(100) NOT NULL,
    PRIVACY  BOOLEAN
)
