CREATE TABLE ROLES
(
    ID   SERIAL PRIMARY KEY,
    ROLE VARCHAR(10) NOT NULL
);

CREATE TABLE USERS
(
    LOGIN    VARCHAR(70) NOT NULL PRIMARY KEY,
    NAME     VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR(30) NOT NULL,
    ROLE_ID  INT NOT NULL,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID)
);